name: naavre-catalogue-service-dev

services:
  db:
    image: postgres:17
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      POSTGRES_PASSWORD: fake-postgres-password

  s3:
    image: quay.io/minio/minio:RELEASE.2025-09-07T16-13-09Z
    command: ["server", "/data", "--console-address", ":9001"]
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    env_file:
      - s3.env
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5

  configure-s3:
    image: quay.io/minio/mc:RELEASE.2025-08-13T08-35-41Z
    depends_on:
      s3:
        condition: service_healthy
    env_file:
      - s3.env
    entrypoint: ["bash", "-e"]
    command: "/configure-s3.sh"
    volumes:
      - ./configure-s3.sh:/configure-s3.sh
