name: CI pipeline

on:
  release:
    types: [published]
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  schedule:
    - cron: '0 4 5,25 * *'


jobs:

  lint:
    if: ${{ needs.configure-workflow.outputs.should_skip != 'true' }}
    uses: ./.github/workflows/lint.yaml

  test:
    if: ${{ needs.configure-workflow.outputs.should_skip != 'true' }}
    uses: ./.github/workflows/test.yaml

  build-docker:
    needs: [lint, test]
    uses: ./.github/workflows/build-docker.yaml
    with:
      oci_tag: ghcr.io/naavre/naavre-catalogue-service
      version: ${{ github.ref_type == 'tag' && github.ref_name || github.sha }}
      push: ${{ github.event_name == 'release' }}

  helm-helm:
    needs: [lint, test]
    uses: ./.github/workflows/build-helm.yaml
    with:
      oci_repo: ghcr.io/naavre/charts
      version: ${{ github.ref_type == 'tag' && github.ref_name || github.sha }}
      push: ${{ github.event_name == 'release' }}
